### ISSUE TITLE
Error after Uptdate to TYPO3 v11 and me_backend_security 3.0.1

### ISSUE THREAD

**Issue by HorstBaumann** [move-elevator/me_backend_security#17]
I updated my website from TYPO3 10.4.34 with me_backend_security 2.0.7 (works fine for 2years)
to TYPO3 11.4.24 and me_backend_security 3.0.1  (PHP 7.4.33)

but now the FrontEnd crashes and shows this error:

Fatal error: Declaration of MoveElevator\MeBackendSecurity\Validation\Validator\CompositeValidator::isValid(MoveElevator\MeBackendSecurity\Validation\Validator\mixed $value): void must be compatible with TYPO3\CMS\Extbase\Validation\Validator\AbstractValidator::isValid($value) in /home/www/public_html/typo3conf/ext/me_backend_security/Classes/Validation/Validator/CompositeValidator.php on line 19

the same error is prompted, when I try to change my password via backend

**Comment by Mainbird** [comment]
Hi :)

did you use composer for extension installation? 

I have checked this extension also with TYPO3 11.5.24 and can not reproduce this error. :(

If you get the extension from TYPO3 TER please try to get the extension from github again, because if I remember correctly there were some issues with the version for TYPO3 TER and I couldn't override the extension with the same version there.

**Comment by HorstBaumann** [comment]
no, its a classic installation via extensionmanager.

OK, installed the git-version, but now the error occurred right after installation and crashes the backend

**Comment by Mainbird** [comment]
Hm sounds weird, but the exception is the same?

I will check this on occasion if you have some patience. I am not using TYPO3 without composer mode anymore, so maybe there is an issue by running non composer mode.

**Comment by HorstBaumann** [comment]
thanks a lot.
the exception in the extensionmanager is the same

**Comment by Mainbird** [comment]
Hi,

I have checked this now and I can confirm your issue with PHP 7.X, because a PHP version constraint is missing inside ext_emconf.php. :(
The current master is not compatible with PHP 7.X anymore and uses type hints like "mixed" which will trigger the issue from above. Composer installations are not affected because the PHP version constraint inside composer.json is set correctly:

```
"require": {
    "php": "^8.0"
},
```

You should not use PHP 7.X anymore too, because PHP 7.X already reached this end of life, see: https://www.php.net/supported-versions.php

Is it possible for you to update your PHP version to 8.X?

I can create a bugfix for this, but this wouldn't really help you because I would add the missing PHP constraint to ext_emconf.php like:

```
'constraints' => [
    'depends' => [
        'php' => '8.0.0-8.9.99',
       'typo3' => '11.5.0-11.5.99',
    ],
],
```

**Comment by HorstBaumann** [comment]
You're right. Switching to PHP8 solved the problem. Thanks a lot for your quick support !

**Comment by Mainbird** [comment]
You are welcome :)
