### ISSUE TITLE
"Passwords don't match" message after try to change Password

### ISSUE THREAD

**Issue by X-Tender** [move-elevator/me_backend_security#6]
I just installed the Plugin on t3 v9. When I try to log in he tells me that I have to change my password, tahts correct because I've setted it to "1 day". But when I enter my old password an d the new one with the correct requirements I get the error that the new passwords doesn't match.

**Comment by danmoebius** [comment]
Hi,

thanks for your report. Could you send me answers to the following questions, please?
What kind of Login is it? Admin or other?
Was the new password different than the old one? 
There are any Error logs in TYPO3 context (TYPO3-Log in typo3temp-Folder or sys_log)? 

best regards

**Comment by X-Tender** [comment]
The User itself is a non admin with a Usergroup.
I've tested various other user config combination and just ran into an another error. I've setted the user as an admin and got this error after tryed to login into BE:

`Session already started by session_start().<br />Make sure no installed extension is starting a session in its ext_localconf.php or ext_tables.php.`

I cleared all cookies but the error appear every time.

Part of the callsatck
![image](https://user-images.githubusercontent.com/1413979/93439133-73ebb500-f8ce-11ea-90d9-dc3dbb893b8c.png)

**Comment by danmoebius** [comment]
Hi, 
did you use any Password-Manager or is the password stored in any KeyChain or browser? 
In this case, the new password field will be filled everytime with the old password. Thus the validation will be failed, because it is the same password. This case is not coverable by extension and the error message is a little bit missleading. But in case of brute force, it won`t be give any advice of the failure. 

best regards

**Comment by X-Tender** [comment]
The PW was not stored in a PW-Manager and was neither used one. And why did a PW-Manager would fill out an old PW in a field where I manual typed in a password?
Or I just didn't understand what exactly the problem is.

**Comment by Mainbird** [comment]
Hi @X-Tender, is it possible to provide some more information to us? :)

- Do you get this issue only on one specific TYPO3 project?
- Can your provide some demo data so I can reproduce your issues?

I have kick started TYPO3 9.5.22, with the following packages:

```
{
    "name": "move-elevator/typo3",
    "description": "TYPO3 Setup",
    "type": "project",
    "minimum-stability": "stable",
    "require": {
        "php": "^7.2",
        "move-elevator/me-backend-security": "^2.0",
        "typo3/cms-belog": "^9.5",
        "typo3/cms-beuser": "^9.5",
        "typo3/cms-setup": "^9.5",
        "typo3/cms-tstemplate": "^9.5",
        "typo3/minimal": "^9.5"
    },
    "require-dev": {
        "roave/security-advisories": "dev-master"
    },
    "config": {
        "sort-packages": true
    }
}
```

but I am currently not able to reproduce your issues :(. So some more information would be very helpful. :)

**Comment by X-Tender** [comment]
I will try your setup and give Feedback.

**Comment by Mainbird** [comment]
Hi @X-Tender, did you test it in the meantime? Any feedback is welcome :)

**Comment by X-Tender** [comment]
Sorry I didn't had the time. I try to make it this week.

**Comment by Mainbird** [comment]
Hi @X-Tender, did you test it in the meantime? I don't want to stress you, but we're about to release this extension for TYPO3 10, but we could not reproduce this bug so far. So any progress is welcome. :)

**Comment by moe2k** [comment]
I can confirm this issue with 

- TYPO3 9.5.21 
- PHP 7.4.7
- move-elevator/me-backend-security v. 2.0.1, also confirmed on 2.0.2 (installed using composer --ignore-platform-reqs because of [this issue here](https://github.com/move-elevator/me_backend_security/issues/7))

On first login, password change is enforced. After submit, a message says that the new passwords don't match.

The user has some groups and is non-admin. Several PW enforcement rules are in place. The user was created through the backend by a non-admin, using koninklijke-collective/my-user-management v. 4.1.0.

**Comment by moe2k** [comment]
@X-Tender do you have typo3/cms-rsaauth installed?

**Comment by Mainbird** [comment]
Hi @moe2k thank you for your feedback. We will fix the version constraint asap and we will check the involvement of koninklijke-collective/my-user-management, because I can't reproduce this issue so far, so maybe koninklijke-collective/my-user-management or any other extension is involved. 

In my test scenarios, I have used your environment settings. Furthermore, I have created several users, sometimes with a user group, sometimes without a user group, sometimes non-admins, sometimes admins. No issues occurred. 

So maybe you can check the following things, too?

- Create a non-admin user with user groups by an admin user account and then walk through the login process with the non-admin user.
- Create a non-admin user without user groups by an admin user account and then walk through the login process with the non-admin user.

**Comment by X-Tender** [comment]
> @X-Tender do you have typo3/cms-rsaauth installed?

Hm I didn't installed it, I will think of it the next time I try to implement the extension.

**Comment by Mainbird** [comment]
Hi @moe2k, I have installed the extension **koninklijke-collective/my-user-management** in the meantime, but I am still not able to reproduce this issue :(. 

In my test scenario, I have created a non-admin user by a non-admin user with and without user groups. In both cases, I was able to set a new password on the first login.

I have also installed the deprecated extension: **typo3/cms-rsaauth** (but you don't need this extension if you already use https and I hope you do). But I couldn't reproduce this issue again and it was still possible to log in to a new non-admin user on the first login.

Can you please check this: https://github.com/move-elevator/me_backend_security/issues/6#issuecomment-741152415 and is it possible to provide a full list of your installed extensions?

Furthermore, any hints and progress are welcome.

**Comment by NamelessCoder** [comment]
Hi @Mainbird,

Referring to the comment by @X-tender at https://github.com/move-elevator/me_backend_security/issues/6#issuecomment-694074302 - so this is only about the "session_start" error:

> In my test scenario, I have created a non-admin user by a non-admin user with and without user groups. In both cases, I was able to set a new password on the first login.

The error is only reproducible with an admin user who is also registered as system maintainer. The reason is this, within `\TYPO3\CMS\Core\Authentication\BackendUserAuthentication::logoff` which gets called when you want to force-logoff the user due to password change:

```php
            if ($this->isSystemMaintainer()) {
                // If user is system maintainer, destroy its possibly valid install tool session.
                $session = new SessionService();
                if ($session->hasSession()) {
                    $session->destroySession();
                }
            }
```

An additional operation to destroy the session happens when the user is a system maintainer, and it is this call to destroy the session which causes the error (because headers have already been sent at this point).

TBH I'm not sure how you could solve this. Perhaps if you detect that the user is a systems administrator, don't force-logoff but instead dispatch a FlashMessage instructing the user to log off or perform some action?

**Comment by moe2k** [comment]
So, the problem does not occur if the user who has to change his password is not a system maintainer (independently from being an administrator), is that correct?

(In our projects, we usually only have one admin which is also system maintainer - so if we know the problem is limited to this account, we already have a relief).

**Comment by Mainbird** [comment]
@NamelessCoder thank you for your detailed feedback. So it seems this issue is related to https://github.com/move-elevator/me_backend_security/issues/4. 

I will check this asap.

**Comment by Mainbird** [comment]
Hi @NamelessCoder, @moe2k I can partly confirm this issue for TYPO3 9.

In my test scenario, I have created an admin account with an admin account. Furthermore, I have added the new admin account to system maintainers. Then I have tried to log in with this new admin account and the error has occurred which @X-Tender and @moe2k mentioned.

The same test scenario works fine without any issues in TYPO3 10 (10.4.10).

But @moe2k and @X-Tender am I wrong or did you have issues with non-admin accounts, too?

**Comment by Mainbird** [comment]
Hi @NamelessCoder, @moe2k, and @X-Tender,

the second issue I can confirm is an issue with RSA encryption enabled. If you have

`'loginSecurityLevel' => 'rsa',`

enabled. TYPO3 will replace the input (password, password confirmation) data via JavaScript through RSA-hashes and these two hashes are not equal, this will finally trigger the "passwords do not match"-Validator.

I guess this test: https://github.com/move-elevator/me_backend_security/issues/6#issuecomment-742338435 was already affected by the RSA encryption. So I will check this again asap.

**Comment by moe2k** [comment]
Confirmed. typo3/cms-rsaauth in combination with that setting leads to the "passwords do not match" error. I've uninstalled rsaauth and set `'loginSecurityLevel' => 'normal'` as the login is SSL-encrypted anyway. That solves the problem for me. IMO it's enough to list this incompatibility in ext_emconf or in the readme.

**Comment by Mainbird** [comment]
Hi, the conflict sections were added to version 2.0.4.

Therefore, I would close this issue now, because there is another open issue for the system maintainer error. Do you agree with that?

**Comment by moe2k** [comment]
Thanks a lot, sounds good to me!
